# Generated by Django 2.0.7 on 2020-09-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gzbd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epidemic',
            options={},
        ),
        migrations.AlterModelTable(
            name='epidemic',
            table='epidemic',
        ),
    ]
