# Generated by Django 2.0.7 on 2020-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coronavirus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis', models.IntegerField(blank=True, null=True)),
                ('overseas_import', models.IntegerField(blank=True, null=True)),
                ('cure', models.IntegerField(blank=True, null=True)),
                ('death', models.IntegerField(blank=True, null=True)),
                ('therapy', models.IntegerField(blank=True, null=True)),
                ('observation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coronavirus',
            },
        ),
    ]
