# Generated by Django 2.0.7 on 2020-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=55, null=True)),
                ('type', models.CharField(blank=True, max_length=55, null=True)),
                ('level', models.CharField(blank=True, max_length=55, null=True)),
                ('nature', models.CharField(blank=True, max_length=55, null=True)),
                ('belong', models.CharField(blank=True, max_length=55, null=True)),
                ('central', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('doublehigh', models.IntegerField(blank=True, null=True)),
                ('f211', models.IntegerField(blank=True, null=True)),
                ('f985', models.IntegerField(blank=True, null=True)),
                ('is_recruitment', models.IntegerField(blank=True, null=True)),
                ('dual_class', models.CharField(blank=True, max_length=55, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('province_name', models.CharField(blank=True, max_length=55, null=True)),
                ('single_province', models.CharField(blank=True, max_length=55, null=True)),
                ('city_name', models.CharField(blank=True, max_length=55, null=True)),
                ('county_name', models.CharField(blank=True, max_length=55, null=True)),
                ('view_total_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
    ]
