# Generated by Django 2.0.7 on 2020-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='user_name')),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
    ]
