# Generated by Django 2.0.7 on 2021-05-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=55, null=True)),
                ('create_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
